### ISSUE TITLE
Reference redmine-net45-api as nuget package

### ISSUE THREAD

**Issue by afcaJordi** [dfensgmbh/biz.dfch.CS.Redmine.Client#10]
The current nuget package (v 0.14.0) of redmine-net45-api contains a bug in serializing the class Upload, which is used to link an attachment to an issue. In the current master branch version this bug is fixed. For the moment I compiled the current master branch version and referenced the dll directly. We should use the new nuget package as soon as it is available.

Repo:
https://github.com/zapadi/redmine-net-api

Nuget:
https://www.nuget.org/packages/redmine-api/

**Comment by rufer7** [comment]
According [issue 134](https://github.com/zapadi/redmine-net-api/issues/134) in the redmine project the NuGet package got updated to version 1.0.0. Actually there is already a newer version ([1.0.2](https://www.nuget.org/packages/redmine-api-signed/)) available.
