### ISSUE TITLE
Update Attachments

### ISSUE THREAD

**Issue by afcaJordi** [dfensgmbh/biz.dfch.CS.Redmine.Client#14]
Updating attachments is not yet supported by the Redmine API.

**Comment by oliverluethi** [comment]
@rufer7 @dfch Added support for updating issue attachments over .NET API and Redmine API.
The Redmine API patch is [here]( http://www.redmine.org/issues/22356).

This feature uses the same method like the issue attachment edit form.

**Comment by rufer7** [comment]
@oliverluethi is this issue solved? If yes, please close it

**Comment by oliverluethi** [comment]
@rufer7 I shelved the changes, because i need the DLL from the forked redmine.net api project. Currently the changes i've made are finally merged into the master branch from the official project. Do we need a new Nuget Package version to get the actual source? 

After that, I can push my changes to the branch.

**Comment by rufer7** [comment]
@oliverluethi yes, we need a NuGet package of the most recent version. Please ask the guy who owns the repository to make a new NuGet release

**Comment by oliverluethi** [comment]
@rufer Adrian Popescu wrote: By the end of the next week a new NuGet package will be available.
So, the package will be available on the 20th of june 2016.

**Comment by oliverluethi** [comment]
According [roadmap](http://www.redmine.org/projects/redmine/roadmap) the fix is not yet planned in one of the next releases as there are still tests missing in the patch

**Comment by oliverluethi** [comment]
@rufer7 @dfch I added the test for this patch. You can find the patch in the [issue](http://www.redmine.org/issues/22356). Here is the actual [patch](http://www.redmine.org/attachments/download/16221/update_attachment_api_with_tests.diff).

**Comment by rufer7** [comment]
According [roadmap](http://www.redmine.org/projects/redmine/roadmap) the [patch](http://www.redmine.org/attachments/download/16221/update_attachment_api_with_tests.diff) tracked by [issue](http://www.redmine.org/issues/22356) will be included in Redmine release `3.4.0`
