### ISSUE TITLE
Add caching for Item sources for selection Properties

### ISSUE THREAD

**Issue by afcaJordi** [dfensgmbh/biz.dfch.CS.Redmine.Client#17]
Caching must be added for:
- [x] Users
- [x] Projects
- [x] Issue States
- [x] Issue Priorities
- [x] Trackers

**Comment by afcaJordi** [comment]
The main problem is with objects that could reach a number greater than 100 because of the page limitations of current Redmine Version (3.2.0). These are the users and the projects. We could cache them in the redmine client instance so it would be possible to clear the cache if a new project or user is added

**Comment by oliverluethi** [comment]
@rufer7 I tested the limitation problem with 1000 projects and 478 Users. There are no limitations. All projects are returned at the same time, the same with users.

Do we need the caching anyway?

**Comment by rufer7** [comment]
@oliverluethi I don't know anything about this problem. Probably @dfch knows something and can give some feedback!?

**Comment by oliverluethi** [comment]
@rufer7 @dfch The current Redmine.Client release uses the `GetObjectList<Project>` method for getting a list of objects. In the new referenced version of the redmine .NET Api this method is obsolete. I changed this to a different `GetObjects<Project>` method instead. This method reads all pages until every record is fetched.

So there is no limit anymore. I've implemented a caching functionality already. If there is no need for this anymore we should consider to close this issue.

**Comment by rufer7** [comment]
@oliverluethi ok nice. Did you implement caching as well for users as mentioned in the comment above from Niklaus Jordi?

**Comment by rufer7** [comment]
@dfch can you please give some feedback here?

**Comment by oliverluethi** [comment]
@rufer7 Probably we won't get any answer here. I did a contribution to the Redmine .NET API for some inheritance fixes for get the caching done on our side.

My commit was merged into the master branch of the zapadi/redmine-net-api [project](https://github.com/zapadi/redmine-net-api/commits/master). 

You did a nuget package for this library right? At some point we have to rebuild the nuget package with the current release. Without these changes, the code will not compile.

**Comment by rufer7** [comment]
@oliverluethi no we did not yet create a NuGet package for `biz.dfch.CS.Redmine.Client`. I would suggest we wait with the creation of a NuGet package until `zapadi/redmine-net-api` gets released. As I saw they are quite active at the moment so I expect we don't have to wait a long time for the next release.
