### ISSUE TITLE
Replace JavaScriptConverter with Newtonsoft.Json

### ISSUE THREAD

**Issue by afcaJordi** [dfensgmbh/biz.dfch.CS.Redmine.Client#5]
The System.Web.Script.Serialization.JavaScriptConverter with Newtonsoft.Json for performance reasons.

**Comment by rufer7** [comment]
@oliverluethi can you please give a short feedback to this issue?

**Comment by oliverluethi** [comment]
@rufer7 The whole application is written with `JavaScriptConverter`. It needs time to refactor this code for `Newtonsoft.Json` to replace every `Converter `class with an equivalent for Newtonsoft. Every converter has to be tested as well.

**Comment by dfch** [comment]
@oliverluethi I see the point, therefore I think we should close the issue
