### ISSUE TITLE
Switch redmine on Lab3 to https

### ISSUE THREAD

**Issue by afcaJordi** [dfensgmbh/biz.dfch.CS.Redmine.Client#9]
Currently redmine on Lab3 uses http. For security reasons it shuold use https.

**Comment by dfch** [comment]
@afcaJordi order a certificate via Olivier and have him install it - keep in mind this is a public repo. Do not disclose internal information or tell me we have to switch to a private repo or track internal issues somewhere else

**Comment by afcaJordi** [comment]
Olivier has changed switched the redmine API to https. All my unit tests work with the new configuration.
